In [1]:
import numpy as np 
import matplotlib.pyplot as plt

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 6, 7])

ymean = np.mean(y)
xmean = np.mean(x)

m = np.sum((x - xmean) * (y - ymean)) / np.sum((x - xmean)**2)
b = ymean - m * xmean

In [2]:
import numpy as np
from sklearn.metrics import accuracy_score

T = 1.0
F = 0.0

def get_OR_data():
    X = np.array([
        [F,F],
        [F,T],
        [T,F],
        [T,T]
    ])
    Y = np.array([
        [F],
        [T],
        [T],
        [T]
    ])
    return X,Y

X,Y = get_OR_data()

class MyPerceptron:
    def __init__(self, learning_rate = 0.1, n = 1000):
        self.lr = learning_rate
        self.epochs = n
        self.weights = None
        self.bias = None
    def fit(self,X,Y):
        self.weights = np.zeros(X.shape[1])
        self.bias = 0
        for epoch in range (self.epochs):
            for i in range(X.shape[0]):
                Y_pred = self.Step_activ_func(np.dot(self.weights,X[i]) + self.bias)
                mae = Y[i]-Y_pred
                self.weights = self.weights + self.lr*mae*X[i]
                self.bias = self.bias + self.lr * mae
    def Step_activ_func(self, activation):
        if (activation >= 0):
            return 1
        else:
            return 0
    def predict(self, X):
        return np.array([self.Step_activ_func(np.dot(self.weights, x) + self.bias) for x in X])

clf = MyPerceptron()
clf.fit(X,Y)

X_test = np.array([
    [F,F],
    [T,F],
    [F,T],
    [F,F]
])
Y_test= np.array([
    [F],
    [T],
    [T],
    [F]
])
Y_predicted = clf.predict(X_test)
print(Y_predicted)
print(accuracy_score(Y_test.ravel(), Y_predicted))


[0 1 1 0]
1.0


In [3]:
import numpy as np
from sklearn.metrics import accuracy_score

T = 1.0
F = 0.0

def get_AND_data():
    X = np.array([
        [F,F],
        [F,T],
        [T,F],
        [T,T]
    ])
    Y = np.array([
        [F],
        [F],
        [F],
        [T]
    ])
    return X,Y

X,Y = get_AND_data()

class MyPerceptron:
    def __init__(self, learning_rate = 0.1, n = 1000):
        self.lr = learning_rate
        self.epochs = n
        self.weights = None
        self.bias = None
    def fit(self,X,Y):
        self.weights = np.zeros(X.shape[1])
        self.bias = 0
        for epoch in range (self.epochs):
            for i in range(X.shape[0]):
                Y_pred = self.Step_activ_func(np.dot(self.weights,X[i]) + self.bias)
                mae = Y[i]-Y_pred
                self.weights = self.weights + self.lr*mae*X[i]
                self.bias = self.bias + self.lr * mae
    def Step_activ_func(self, activation):
        if (activation >= 0):
            return 1
        else:
            return 0
    def predict(self, X):
        return np.array([self.Step_activ_func(np.dot(self.weights, x) + self.bias) for x in X])

clf = MyPerceptron()
clf.fit(X,Y)

X_test = np.array([
    [F,F],
    [T,F],
    [F,T],
    [T,T]
])
Y_test= np.array([
    [F],
    [F],
    [F],
    [T]
])
Y_predicted = clf.predict(X_test)
print(Y_predicted)
print(accuracy_score(Y_test.ravel(), Y_predicted))

[0 0 0 1]
1.0


In [4]:
import numpy as np
from sklearn.metrics import accuracy_score

T = 1.0
F = 0.0

def get_NAND_data():
    X = np.array([
        [F,F],
        [F,T],
        [T,F],
        [T,T]
    ])
    Y = np.array([
        [T],
        [T],
        [T],
        [F]
    ])
    return X,Y

X,Y = get_NAND_data()

class MyPerceptron:
    def __init__(self, learning_rate = 0.1, n = 1000):
        self.lr = learning_rate
        self.epochs = n
        self.weights = None
        self.bias = None
    def fit(self,X,Y):
        self.weights = np.zeros(X.shape[1])
        self.bias = 0
        for epoch in range (self.epochs):
            for i in range(X.shape[0]):
                Y_pred = self.Step_activ_func(np.dot(self.weights,X[i]) + self.bias)
                mae = Y[i]-Y_pred
                self.weights = self.weights + self.lr*mae*X[i]
                self.bias = self.bias + self.lr * mae
    def Step_activ_func(self, activation):
        if (activation >= 0):
            return 1
        else:
            return 0
    def predict(self, X):
        return np.array([self.Step_activ_func(np.dot(self.weights, x) + self.bias) for x in X])

clf = MyPerceptron()
clf.fit(X,Y)

X_test = np.array([
    [F,F],
    [T,F],
    [F,T],
    [T,T]
])
Y_test= np.array([
    [T],
    [T],
    [T],
    [F]
])
Y_predicted = clf.predict(X_test)
print(Y_predicted)
print(accuracy_score(Y_test.ravel(), Y_predicted))

[1 1 1 0]
1.0


In [5]:
import numpy as np
from sklearn.metrics import accuracy_score

T = 1.0
F = 0.0

def get_NOR_data():
    X = np.array([
        [F,F],
        [F,T],
        [T,F],
        [T,T]
    ])
    Y = np.array([
        [T],
        [F],
        [F],
        [F]
    ])
    return X,Y

X,Y = get_NOR_data()

class MyPerceptron:
    def __init__(self, learning_rate = 0.1, n = 1000):
        self.lr = learning_rate
        self.epochs = n
        self.weights = None
        self.bias = None
    def fit(self,X,Y):
        self.weights = np.zeros(X.shape[1])
        self.bias = 0
        for epoch in range (self.epochs):
            for i in range(X.shape[0]):
                Y_pred = self.Step_activ_func(np.dot(self.weights,X[i]) + self.bias)
                mae = Y[i]-Y_pred
                self.weights = self.weights + self.lr*mae*X[i]
                self.bias = self.bias + self.lr * mae
    def Step_activ_func(self, activation):
        if (activation >= 0):
            return 1
        else:
            return 0
    def predict(self, X):
        return np.array([self.Step_activ_func(np.dot(self.weights, x) + self.bias) for x in X])

clf = MyPerceptron()
clf.fit(X,Y)

X_test = np.array([
    [F,F],
    [T,F],
    [F,T],
    [F,F]
])
Y_test= np.array([
    [T],
    [F],
    [F],
    [T]
])
Y_predicted = clf.predict(X_test)
print(Y_predicted)
print(accuracy_score(Y_test.ravel(), Y_predicted))

[1 0 0 1]
1.0


In [6]:
import numpy as np
from sklearn.metrics import accuracy_score

T = 1.0
F = 0.0

def get_XOR_data():
    X = np.array([
        [F,F],
        [F,T],
        [T,F],
        [T,T]
    ])
    Y = np.array([
        [F],
        [T],
        [T],
        [F]
    ])
    return X,Y

X,Y = get_XOR_data()

class MyPerceptron:
    def __init__(self, learning_rate = 0.1, n = 1000):
        self.lr = learning_rate
        self.epochs = n
        self.weights = None
        self.bias = None
    def fit(self,X,Y):
        self.weights = np.zeros(X.shape[1])
        self.bias = 0
        for epoch in range (self.epochs):
            for i in range(X.shape[0]):
                Y_pred = self.Step_activ_func(np.dot(self.weights,X[i]) + self.bias)
                mae = Y[i]-Y_pred
                self.weights = self.weights + self.lr*mae*X[i]
                self.bias = self.bias + self.lr * mae
    def Step_activ_func(self, activation):
        if (activation >= 0):
            return 1
        else:
            return 0
    def predict(self, X):
        return np.array([self.Step_activ_func(np.dot(self.weights, x) + self.bias) for x in X])

clf = MyPerceptron()
clf.fit(X,Y)

X_test = np.array([
    [F,F],
    [T,F],
    [F,T],
    [F,F]
])
Y_test= np.array([
    [F],
    [T],
    [T],
    [F]
])
Y_predicted = clf.predict(X_test)
print(Y_predicted)
print(accuracy_score(Y_test.ravel(), Y_predicted))

[1 0 1 1]
0.25
